### ISSUE TITLE
Physical user interface

### ISSUE THREAD

**Issue by kaolpr** [gkasprow/MicroTCA-chassis#12]
Suggested changes after chat with @gkasprow:

- change display to something cheaper, e.g. OLED SSD1306 based like this:
![image](https://user-images.githubusercontent.com/9166701/145996573-e3c76b03-8a03-4780-a8e6-30ad7adf47ca.png)
- rearrange buttons in a bit more intuitive way:
![image](https://user-images.githubusercontent.com/9166701/145996414-0561c7de-8e61-4cdd-a4e0-6e1ef6a8806e.png)
- add RGB LED for generalized status (so that one can know that operation is OK with just a glimpse on the device),
- add buzzer on the main board.

Physical user interface on the front panel would be used for basic configuration and status:

- generalized status via RGB LED and information on the OLED display,
- buzzer for critical warnings,
- display IP address for WiFi and cable connection,
- enable configuration hot-spot for network configuration,
- for power enable,
- display JTAG configuration,
- display power supply status (power rail status + currents).

**Comment by gkasprow** [comment]
It would be good to check if existing network config tools use some form of keyboard and implement it in the same manner.
