### ISSUE TITLE
X1 has invalid footprint and missing pins

### ISSUE THREAD

**Issue by kaolpr** [gkasprow/MicroTCA-chassis#4]
It appears that given part number for X1 (NX3225GA-25.000M-STD-CRG-2) has 4 pins and size incompatible with chosen footprint. 

https://eu.mouser.com/datasheet/2/905/c_NX3225GA-STD-CRG-2_e-1317529.pdf

**Comment by gkasprow** [comment]
not valid anymore, we are changing the MCU
