### ISSUE TITLE
Front panel connectors

### ISSUE THREAD

**Issue by kaolpr** [gkasprow/MicroTCA-chassis#7]
Suggested set of front panel connectors:

- management Ethernet,
- 6x SFP (ports 0,1, 4-7),
- 2x RJ45 for MLVDS,
- microUSB for SBC serial,
- [new] management WiFi SMA (SMA-u.FL cable),
- [new] TCLKA SMA (SMA-u.FL from the mainboard),
- [new] TCLKB SMA (SMA-u.FL from the mainboard).

**Comment by gkasprow** [comment]
what about a micro-USB UART?
One USB host for the programmer would be inside, do we need another one on the front panel? I don't see any use case for one

**Comment by kaolpr** [comment]
> what about a micro-USB UART?

Yes, I forgot about it. Editing comment.

> One USB host for the programmer would be inside, do we need another one on the front panel? I don't see any use case for one

I don't think putting USB host on FP is of any use.

**Comment by gkasprow** [comment]
So the conclusion is that we need:
- USB UART on the panel
- USB A host on the mainboard for the external programmer, but installed still inside of the enclosure
- USB host permanently routed to the embedded JTAG programmer.
